worldmap/index.html
Do the same code for each Element of the array
=> Add capability to pass in an Array of Data to the Node

worldmap/index.html
Bounds are a 2 Dimensional Array that define the top left and bottom right coordinates (lat lng) wher the Image should be placed
=> Added Capability for ImageOverlay

worldmap/index.html
User can now specify:
- color
- fillColor
- stroke
- weight
- opacity
- fillOpacity
- fill
- clickable (if true sets the passed in name as Popup)
The same standard settings as before where kept.
=> Allow user to pass trough more options

worldmap/index.html
the developer expects identical behavior as with the other overlays/base layers
=> Passing in opt to imageOverlay

worldmap.html, worldmap.js
Sorry for dropping the ball... I got distracted...
I tested your commit and made some improvements, merge if you like...
- added some info text
- add leading '/' to map path without which the map doesn't work
=> multimap tweaks

README.md, worldmap/index.html
Search using a search command:
msg.payload = { command:{search:"us10"} };
and clearing it using the following:
msg.payload = { command:{search:"clear"} };
=> Basic Dynamic Search Control using the command

worldmap/index.html
dashArray property was left out, adding it to options handler passing dashArray property to leaflet.
=> Pass dashArray property to leaflet

worldmap.html, worldmap.js
Added new `ui_worldmap` node hat can display map on the Node-RED Dashboard.
This node is a simple wrapper around  `worldmap` node using `iframe`.
Since this node shares runtime code with `worldmap` node, I have put it in the same package.
But it may be better to make it in separate package.
=> add new ui_worldmap node for displaying map on Node-RED Dashboard

README.md, worldmap/worldmap.js
Allow users to send an array of objects to allow multiple weblink's
=> enhancement - multiple weblink's

worldmap.js
=> add _sessionip of the user connected to a _sessionid

README.md
=> Revert "documentation for redirect"

worldmap/index.html, worldmap/worldmap.js
Toplogo could be change by payload : (from request #187 )
msg.payload = {command:{"toplogo":"/path/to/img.png"}}
return msg;
=> Hide or customize "Node-RED Map All The Things" Header

worldmap/worldmap.js
This information is send by osrm so could it be add to the event ?
Thanks
=> Add distance and duration to project-osrm result

README.md
sorry just noticed it when I tried to use it by copying from doc's  this should fix it.
=> Syntax error- forgot [ " ] - Update README.md

README.md
I forgot to document the _sessionip pull I created and you committed years ago. figured I would add a blip on it as well for anyone using CTRL+F
Please read and change any explanation to how you think it should sound.
=> Update README.md for _clientheaders and _sessionip

README.md
Document the function of msg.payload.clientTimezone
Also added documentation for msg.payload.parameters
=> Update README.md - clientTimezone

.gitignore, examples/feedback.json, worldmap/worldmap.js
- Add ${name} handling to popups,
- Fix contextmenu feedback exception for shape items.
- Simplify feedback logic
- Add example of feedback flow
=> Fix to issue 268

README.md, examples/sidcEdgeIcon.json, worldmap/worldmap.js
Add sidcEdgeIcon option to enable/disable the icons display
Add sidcEdgeIcon example flow file
=> SIDC map edge icon display option

worldmap/worldmap.js
Works better with 
`Array.isArray`
;-)
=> Fix isArray exception

README.md
Fix documentation error for sidcEdgeIcon  flag
=> DOC - Fix sidcEdgeIcon flag name in README.md

examples/Moving Icons Demo & Builder.json
=> Add iconSize option to Moving Icons Demo & Build example
